
/*
export const USER_EXISTS = "you already have account";
export const THIS_USER_EXISTS = "this user exists";
export const THIS_EMAIL_EXISTS = "email assigned to another user";
export const OUR_USER_ADDED = "our user added";
export const ALREADY_HAS_WALLET = (cur_type)=> `already has a <span style='color : blue'>${cur_type}</span> wallet`;
export const WRONG_EMAIL = "wrong credentials";
export const WRONG_PASSWORD = "wrong credentials";
export const AVAILABLE = "Available";
export const NOT_AVAILABLE = "Name is used before";
export const TOKEN_ERROR = "Can't sign or verify token";
export const PASSWORD_ERROR = "Password Error";
export const USER_NOT_FOUND_ERROR = "user not found";
export const ADMIN_NOT_FOUND_ERROR = "admin not found";
export const Empty_Credentials_ERROR = "empty credentials";
export const WRONG_MEMBERSHIP_NUMBER = "wrong membership number";
export const Email_ERROR = "Email not found";
export const EXPIRED_OTP = "Expired OTP <br> Request a new one please";
export const WRONG_OTP = "Wrong OTP";
export const NO_OTP_FOR_THIS_EMAIL = "No OTP Sent for this email <br> Request a new one please";
export const NOT_SUCH_WALLET = "No such wallet";
export const NOT_SUFFICIENT_AMOUNT = "Not sufficient amount";
export const WITHDRAW_SUCCESSFUL = "Withdraw Successful";
export const WRONG_KEY = "Wrong Key";
export const WRONG_AMOUNT = "Wrong amount";
export const NO_NETWORK_WITH_THAT_NAME = "network name not found";
export const NO_DEPOSIT_ADDRESS_AVAILABLE = "no deposit address";
export const NO_USER_WITH_THAT_NAME = "no user with that name available";
export const NO_USER_WITH_THAT_Email = "no user with that email available";
export const THIS_EMAIL_IS_USED = "this email is used by another user .";
export const YOU_CANT_TRANSFER_TO_YOURSELF = "you can't transfer to yourself";
export const YOU_MUST_BE_VIP1 = "you must be at least <span style='color:blue'>VIP1</span> to transfer funds";
export const YOU_MUST_BE_VIP1_TO_WITHDRAW = "you must be at least <span style='color:blue'>VIP1</span> to withdraw funds";
export const YOU_MUST_BE_VIP1_TO_DEPOSIT = "you must be at least <span style='color:blue'>VIP1</span> to deposit funds";
export const HE_MUST_BE_VIP1 = "the receiver must be at least <span style='color:blue'>VIP1</span> to receive funds";
export const TRANSFER_SUCCESSFUL = "Transfer Successful";
export const EXCHANGE_SUCCESSFUL = "Exchange Successful";
export const EMAIL_EDIT_SUCCESSFUL = "Email Successfully Edited";
export const FEE_EDITED = "Fee Edited";
export const MAX_RECEIVE_EDITED = "max receive Edited";
export const MAX_TRANSFER_EDITED = "max transfer Edited";
export const MAX_WITHDRAW_EDITED = "max withdraw Edited";
export const MAX_DEPOSIT_EDITED = "max deposit Edited";
export const MEM_REMOVED = "membership removed";
export const CONV_RATE_ADDED_UPDATED = "conv rate added/updated";
export const CONV_RATE_REMOVED = "conv rate removed";
export const MEM_ADDED = "membership added";
export const VIP_EDITED = "Vip Edited";
export const WALLET_UPDATED = "Wallet Updated";
export const WALLET_ADDED = "Wallet Added";
export const WALLET_REMOVED = "Wallet Removed";
export const MEMBERSHIP_EXISTS = "membership already exists";
export const NO_MEMBERSHIP_WITH_THAT_TYPE = "no membership with that type";
export const NO_MEMBERSHIP_WITH_THAT_NUMBER = "no membership with that number";
export const NOT_ENOUGH_USDT_BALANCE = "NOT Enough <span style='color:blue'>USDT</span> Balance";
export const NO_USDT_WALLET = "You have no <span style='color:blue'>USDT</span> wallet";
export const TRANSACTION_ID_ERROR = "transaction id ERROR";
export const TRANSACTION_DOC_DELETED = "transaction id deleted";
export const UPGRADED_USER = "user upgraded successful";
export const TRANSACTION_ID_SAVED = (vip_type) => `<span style='color:green'>${vip_type.toUpperCase()}</span> Membership <br> It takes <span style='color:blue'>12 hrs</span> Max to review .`;
export const BASIC_TRANSFER_LIMIT_ERROR = (receiverNameOrEmail,maxToBeInWallet,cur_type) => `<span style='color:black'>${receiverNameOrEmail}</span> is <span style='color:blue'>Basic</span> so he/she can't receive this amount as his wallet will exceed the limit of <span style='color:black;font-style:italic'>${maxToBeInWallet.toString()}</span> <span style='color:blue'>${cur_type}</span>`;

//===================================== ar ==============================================
export const USER_EXISTS = "لديك حساب بالفعل";
export const THIS_USER_EXISTS = "هذا المستخدم موجود";
export const THIS_EMAIL_EXISTS = "البريد الإلكتروني مستخدم من قبل مستخدم آخر";
export const OUR_USER_ADDED = "تمت إضافة المستخدم الخاص بنا";
export const ALREADY_HAS_WALLET = (cur_type) => `يمتلك بالفعل محفظة <span style='color : blue'>${cur_type}</span>`;
export const WRONG_EMAIL = "بيانات الاعتماد خاطئة";
export const WRONG_PASSWORD = "بيانات الاعتماد خاطئة";
export const AVAILABLE = "متاح";
export const NOT_AVAILABLE = "الاسم مستخدم من قبل";
export const TOKEN_ERROR = "لا يمكن توقيع أو التحقق من الرمز";
export const PASSWORD_ERROR = "خطأ في كلمة المرور";
export const USER_NOT_FOUND_ERROR = "المستخدم غير موجود";
export const ADMIN_NOT_FOUND_ERROR = "المسؤول غير موجود";
export const Empty_Credentials_ERROR = "بيانات الاعتماد فارغة";
export const WRONG_MEMBERSHIP_NUMBER = "رقم العضوية خاطئ";
export const Email_ERROR = "البريد الإلكتروني غير موجود";
export const EXPIRED_OTP = "رمز التحقق منتهي <br> الرجاء طلب رمز جديد";
export const WRONG_OTP = "رمز التحقق خاطئ";
export const NO_OTP_FOR_THIS_EMAIL = "لم يتم إرسال رمز تحقق لهذا البريد الإلكتروني <br> الرجاء طلب رمز جديد";
export const NOT_SUCH_WALLET = "لا توجد محفظة بهذا الاسم";
export const NOT_SUFFICIENT_AMOUNT = "المبلغ غير كافٍ";
export const WITHDRAW_SUCCESSFUL = "تم السحب بنجاح";
export const WRONG_KEY = "المفتاح خاطئ";
export const WRONG_AMOUNT = "المبلغ خاطئ";
export const NO_NETWORK_WITH_THAT_NAME = "اسم الشبكة غير موجود";
export const NO_DEPOSIT_ADDRESS_AVAILABLE = "لا يوجد عنوان إيداع";
export const NO_USER_WITH_THAT_NAME = "لا يوجد مستخدم بهذا الاسم";
export const NO_USER_WITH_THAT_Email = "لا يوجد مستخدم بهذا البريد الإلكتروني";
export const THIS_EMAIL_IS_USED = "هذا البريد الإلكتروني مستخدم من قبل مستخدم آخر.";
export const YOU_CANT_TRANSFER_TO_YOURSELF = "لا يمكنك التحويل إلى نفسك";
export const YOU_MUST_BE_VIP1 = "يجب أن تكون على الأقل <span style='color:blue'>VIP1</span> لتحويل الأموال";
export const YOU_MUST_BE_VIP1_TO_WITHDRAW = "يجب أن تكون على الأقل <span style='color:blue'>VIP1</span> لسحب الأموال";
export const YOU_MUST_BE_VIP1_TO_DEPOSIT = "يجب أن تكون على الأقل <span style='color:blue'>VIP1</span> لإيداع الأموال";
export const HE_MUST_BE_VIP1 = "يجب أن يكون المستلم على الأقل <span style='color:blue'>VIP1</span> لتلقي الأموال";
export const TRANSFER_SUCCESSFUL = "تم التحويل بنجاح";
export const EXCHANGE_SUCCESSFUL = "تم التبادل بنجاح";
export const EMAIL_EDIT_SUCCESSFUL = "تم تعديل البريد الإلكتروني بنجاح";
export const FEE_EDITED = "تم تعديل الرسوم";
export const MAX_RECEIVE_EDITED = "تم تعديل الحد الأقصى للاستلام";
export const MAX_TRANSFER_EDITED = "تم تعديل الحد الأقصى للتحويل";
export const MAX_WITHDRAW_EDITED = "تم تعديل الحد الأقصى للسحب";
export const MAX_DEPOSIT_EDITED = "تم تعديل الحد الأقصى للإيداع";
export const MEM_REMOVED = "تمت إزالة العضوية";
export const CONV_RATE_ADDED_UPDATED = "تمت إضافة/تحديث معدل التحويل";
export const CONV_RATE_REMOVED = "تمت إزالة معدل التحويل";
export const MEM_ADDED = "تمت إضافة العضوية";
export const VIP_EDITED = "تم تعديل العضوية المميزة";
export const WALLET_UPDATED = "تم تحديث المحفظة";
export const WALLET_ADDED = "تمت إضافة المحفظة";
export const WALLET_REMOVED = "تمت إزالة المحفظة";
export const MEMBERSHIP_EXISTS = "العضوية موجودة بالفعل";
export const NO_MEMBERSHIP_WITH_THAT_TYPE = "لا توجد عضوية بهذا النوع";
export const NO_MEMBERSHIP_WITH_THAT_NUMBER = "لا توجد عضوية بهذا الرقم";
export const NOT_ENOUGH_USDT_BALANCE = "لا يوجد رصيد كافٍ من <span style='color:blue'>USDT</span>";
export const NO_USDT_WALLET = "ليس لديك محفظة <span style='color:blue'>USDT</span>";
export const TRANSACTION_ID_ERROR = "خطأ في معرف المعاملة";
export const TRANSACTION_DOC_DELETED = "تم حذف معرف المعاملة";
export const UPGRADED_USER = "تم ترقية المستخدم بنجاح";
export const TRANSACTION_ID_SAVED = (vip_type) => `<span style='color:green'>${vip_type.toUpperCase()}</span> عضوية <br> يستغرق الأمر <span style='color:blue'>12 ساعة</span> كحد أقصى للمراجعة.`;
export const BASIC_TRANSFER_LIMIT_ERROR = (receiverNameOrEmail, maxToBeInWallet, cur_type) => `<span style='color:black'>${receiverNameOrEmail}</span> هو <span style='color:blue'>أساسي</span> لذا لا يمكنه استلام هذا المبلغ لأن محفظته ستتجاوز الحد الأقصى البالغ <span style='color:black;font-style:italic'>${maxToBeInWallet.toString()}</span> <span style='color:blue'>${cur_type}</span>`;
*/