
export const USER_EXISTS = "you already have account";
export const WRONG_EMAIL = "wrong credentials";
export const WRONG_PASSWORD = "wrong credentials";
export const AVAILABLE = "Available";
export const NOT_AVAILABLE = "Name is used before";
export const TOKEN_ERROR = "Can't sign or verify token";
export const PASSWORD_ERROR = "Password Error";
export const USER_NOT_FOUND_ERROR = "user not found";
export const ADMIN_NOT_FOUND_ERROR = "admin not found";
export const Empty_Credentials_ERROR = "empty credentials";
export const Email_ERROR = "Email not found";
export const EXPIRED_OTP = "Expired OTP <br> Request a new one please";
export const WRONG_OTP = "Wrong OTP";
export const NO_OTP_FOR_THIS_EMAIL = "No OTP Sent for this email <br> Request a new one please";
export const NOT_SUCH_WALLET = "No such wallet";
export const NOT_SUFFICIENT_AMOUNT = "Not sufficient amount";
export const WITHDRAW_SUCCESSFUL = "Withdraw Successful";
export const WRONG_KEY = "Wrong Key";
export const WRONG_AMOUNT = "Wrong amount";
export const NO_NETWORK_WITH_THAT_NAME = "network name not found";
export const NO_DEPOSIT_ADDRESS_AVAILABLE = "no deposit address";
export const NO_USER_WITH_THAT_NAME = "no user with that name available";
export const NO_USER_WITH_THAT_Email = "no user with that email available";
export const THIS_EMAIL_IS_USED = "this email is used by another user .";
export const YOU_CANT_TRANSFER_TO_YOURSELF = "you can't transfer to yourself";
export const YOU_MUST_BE_VIP1 = "you must be at least <span style='color:blue'>VIP1</span> to transfer funds";
export const YOU_MUST_BE_VIP1_TO_WITHDRAW = "you must be at least <span style='color:blue'>VIP1</span> to withdraw funds";
export const YOU_MUST_BE_VIP1_TO_DEPOSIT = "you must be at least <span style='color:blue'>VIP1</span> to deposit funds";
export const HE_MUST_BE_VIP1 = "the receiver must be at least <span style='color:blue'>VIP1</span> to receive funds";
export const TRANSFER_SUCCESSFUL = "Transfer Successful";
export const EXCHANGE_SUCCESSFUL = "Exchange Successful";
export const EMAIL_EDIT_SUCCESSFUL = "Email Successfully Edited";
export const MEMBERSHIP_EXISTS = "membership already exists";
export const NO_MEMBERSHIP_WITH_THAT_TYPE = "no membership with that type";
export const NO_MEMBERSHIP_WITH_THAT_NUMBER = "no membership with that number";
export const NOT_ENOUGH_USDT_BALANCE = "NOT Enough <span style='color:blue'>USDT</span> Balance";
export const NO_USDT_WALLET = "You have no <span style='color:blue'>USDT</span> wallet";
export const TRANSACTION_ID_ERROR = "transaction id ERROR";
export const TRANSACTION_DOC_DELETED = "transaction id deleted";
export const UPGRADED_USER = "user upgraded successful";
export const TRANSACTION_ID_SAVED = (vip_type) => `<span style='color:green'>${vip_type.toUpperCase()}</span> Membership <br> It takes <span style='color:blue'>12 hrs</span> Max to review .`;
export const BASIC_TRANSFER_LIMIT_ERROR = (receiverNameOrEmail,maxToBeInWallet,cur_type) => `<span style='color:black'>${receiverNameOrEmail}</span> is <span style='color:blue'>Basic</span> so he/she can't receive this amount as his wallet will exceed the limit of <span style='color:black;font-style:italic'>${maxToBeInWallet.toString()}</span> <span style='color:blue'>${cur_type}</span>`;
